version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: buzz-db
    ports:
      - 3309:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin!09
      TZ: Asia/Seoul
      MYSQL_DATABASE: buzz_database
      MYSQL_USER: buzz
      MYSQL_PASSWORD: buzz
    command:
      - --character-set-server=UTF8MB4
      - --collation-server=UTF8MB4_UNICODE_CI